# Generated by Django 3.2 on 2021-10-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Imagen del Producto', 'verbose_name_plural': 'Imagenes del Producto'},
        ),
        migrations.AlterModelOptions(
            name='productspecificationvalue',
            options={'verbose_name': 'Tipo de Producto', 'verbose_name_plural': 'Tipos de Producto'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Not Required', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'El precio debe estar entre 0 y 999.99.'}}, help_text='Máximo 999.99', max_digits=5, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='productspecificationvalue',
            name='value',
            field=models.CharField(help_text='Tipo de Producto', max_length=255, verbose_name='Valor'),
        ),
    ]
