# Generated by Django 3.2 on 2021-11-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryoptions',
            name='delivery_method',
            field=models.CharField(choices=[('IS', 'In Store'), ('HD', 'Home Delivery')], help_text='Required', max_length=255, verbose_name='delivery_method'),
        ),
    ]
